# Site settings
# These are used to personalize your new site.
title: Ponpawit Potisom # your name here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Cyber Security (class of 2027)
  <br /><br />
  <a href="">View My Resume</a>
  <br /><br />
  <a href="www.linkedin.com/in/ponpawit-potisom">View My LinkedIn Profile</a>
repository: "csci-csu/csci-portfolio"
github_username:  ppotisom-pp # update with your username
google_analytics: 377845720 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

